# Generated by Django 3.0.7 on 2020-06-18 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Restoration & Renovation', 'Tenant Turns'), ('Property Maintenance', 'none')], default='none', max_length=30)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('mob_number', models.CharField(max_length=250)),
                ('message', models.TextField(blank=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'in processing'), ('complete', 'accepted')], default='new', max_length=30)),
            ],
        ),
    ]
