# Generated by Django 3.0.7 on 2020-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.CharField(choices=[('Restoration & Renovation', 'Restoration & Renovation'), ('Tenant Turns', 'Tenant Turns'), ('Property Maintenance', 'Property Maintenance'), ('none', 'none')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('complete', 'Complete'), ('in processing', 'In processing'), ('accepted', 'Accepted')], default='new', max_length=30),
        ),
    ]
